services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./code:/var/www/html
    networks:
      - app-network

  # PostgreSQL Service
  postgres:
    build:
      context: .
      dockerfile: psql.dockerfile
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: security_cw2
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Nginx Service
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code:/var/www/html
      - ./nginx/sites:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      - app-network

  # Mailhog Service
  mailhog:
    build:
      context: .
      dockerfile: mailhog.dockerfile
    container_name: mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
